table dim_sellers
	lineageTag: a7686b37-6576-456b-b337-8644e2603bc2

	column seller_id
		dataType: string
		lineageTag: 5630f155-12b9-47c6-8029-37202c81e605
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column seller_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: a6d7b1e1-609f-4613-bf68-433c8f777ae5
		summarizeBy: sum
		sourceColumn: seller_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column seller_city
		dataType: string
		lineageTag: 1a6fad21-032b-4f39-ab69-12ded26fcf97
		summarizeBy: none
		sourceColumn: seller_city

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: ce31efa0-1e40-46a9-abeb-0cdbce8bb434
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	column gold_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: b63b520d-4d46-471a-8865-544a4c3dabca
		summarizeBy: none
		sourceColumn: gold_updated_at

		variation Variation
			isDefault
			relationship: 680d8039-34f8-48ff-a0b7-7028a3f85567
			defaultHierarchy: LocalDateTable_e3a2cc18-fc8c-424b-a96f-62ee1194f03e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition dim_sellers = m
		mode: import
		source =
				let
				    Source = gold_dwh,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Table name] = "dim_sellers")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (5)", each #"Transform File (5)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (5)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (5)", Table.ColumnNames(#"Transform File (5)"(#"Sample File (5)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"seller_id", type text}, {"seller_zip_code_prefix", Int64.Type}, {"seller_city", type text}, {"seller_state", type text}, {"gold_updated_at", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

