table dim_products
	lineageTag: 35d263f3-815e-46e4-82b5-38b111cae41e

	column product_id
		dataType: string
		lineageTag: 9695998c-19ad-48d1-aec4-d82834ebe1e0
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: a970dcae-13ec-4cc5-9580-a7dc54287c43
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column volume_cm3
		dataType: int64
		formatString: 0
		lineageTag: 4d486b43-8682-4713-a2b5-e105affb94af
		summarizeBy: sum
		sourceColumn: volume_cm3

		annotation SummarizationSetBy = Automatic

	column weight_g
		dataType: int64
		formatString: 0
		lineageTag: 3e68d221-c9df-49fc-8b65-4441a8317625
		summarizeBy: sum
		sourceColumn: weight_g

		annotation SummarizationSetBy = Automatic

	column gold_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 0f5b1dee-26df-427c-959b-100d5164a31b
		summarizeBy: none
		sourceColumn: gold_updated_at

		variation Variation
			isDefault
			relationship: 18016621-6a96-4c27-a0f5-fcb2a6365d6b
			defaultHierarchy: LocalDateTable_72cd3ab4-c200-4bb2-b6a9-d65de6e26ac0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition dim_products = m
		mode: import
		source =
				let
				    Source = gold_dwh,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Table name] = "dim_products")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (4)", each #"Transform File (4)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (4)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (4)", Table.ColumnNames(#"Transform File (4)"(#"Sample File (4)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"product_id", type text}, {"category", type text}, {"volume_cm3", Int64.Type}, {"weight_g", Int64.Type}, {"gold_updated_at", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

