table dim_customers
	lineageTag: 82d947cf-fa41-4631-8d40-3d8b753929a3

	column customer_id
		dataType: string
		lineageTag: a4828523-dcfc-40d8-93bc-1630cec8e2de
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 0bb306a1-34b1-42bc-b2fe-39d23f5ce5d3
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 403be195-656c-444c-b7f3-aeb83f46e504
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 1c7121c2-9469-47de-85f4-b8db7c8819aa
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 3611cef2-08e1-4114-ab75-fbf1fc0b4510
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column gold_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: ec138983-6f7e-423d-b764-ca922513a664
		summarizeBy: none
		sourceColumn: gold_updated_at

		variation Variation
			isDefault
			relationship: 86062e95-5c68-4965-88ae-ef1449061133
			defaultHierarchy: LocalDateTable_20feec38-3d4b-4f85-9e8c-9a6635337ffe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		source =
				let
				    Source = gold_dwh,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Table name] = "dim_customers")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}, {"gold_updated_at", type datetime}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"customer_unique_id"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Duplicates", each [customer_unique_id] <> null and [customer_unique_id] <> "")
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

