table dim_date
	lineageTag: 0655958d-5779-4be6-8bb1-1c3d9e86254c

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 7c8a16ce-2e5b-4220-bfdc-f6a6e17df3d3
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 822b0f49-c49d-4cd7-9e7c-e371e3f55e17
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 3452711d-bcb5-4d58-97c1-9fef811b5f4d
			defaultHierarchy: LocalDateTable_66fa8c90-b867-41a4-a2c8-dbe97ec35ddf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: f43cb5cf-c21c-4385-a6ed-72a3ddf0404f
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: 441e9bf6-d09e-4b32-965f-f953d205b947
		summarizeBy: sum
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 314d5a68-2ccd-4a02-af34-2ffe1facbb35
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 38c26d4a-614a-42fb-8deb-d6a5c0c1e55b
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 9649efc2-b010-43b8-a22a-817d0c2a8ab5
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column gold_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 41282163-eab1-44ef-9afb-4f96c63061d1
		summarizeBy: none
		sourceColumn: gold_updated_at

		variation Variation
			isDefault
			relationship: 5a198677-a160-4afb-8bfb-a3c790c2112d
			defaultHierarchy: LocalDateTable_a5c61c92-bb36-4c88-8e0f-4ee36aa9634c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = gold_dwh,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Table name] = "dim_date")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (3)", each #"Transform File (3)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (3)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (3)", Table.ColumnNames(#"Transform File (3)"(#"Sample File (3)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"month", Int64.Type}, {"quarter", Int64.Type}, {"day_name", type text}, {"month_name", type text}, {"gold_updated_at", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

