table fact_orders
	lineageTag: e80c3aa9-ad9a-4b38-8387-f0a1743f14a0

	column order_id
		dataType: string
		lineageTag: fe13e90b-c562-4534-a512-fc0f4481d3bd
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 4bff52ea-ee22-4f64-80eb-d0aa226ef3ab
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column order_date_key
		dataType: int64
		formatString: 0
		lineageTag: 10718cee-c3b0-4876-9884-356989876466
		summarizeBy: none
		sourceColumn: order_date_key

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: c769a8f4-477d-4b41-a3ad-3289271817c1
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 5380d544-c1d8-4d99-bd0e-037df069b503
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: ebb0856d-d14b-4762-8cca-d2673f64ff5a
			defaultHierarchy: LocalDateTable_776a4906-135b-460f-90ba-cbe43e5a5e01.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f05ea690-e83c-4fd5-adc6-61dd899b191e
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: 8077f670-ba90-49be-bb5c-abc4d88a2c37
			defaultHierarchy: LocalDateTable_3d314933-692e-4b91-9453-706db468f426.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3769ee7b-2873-4c09-8a34-2d01b3ee2ea1
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: cc56dbe8-4ee8-4e49-8150-9a170d220aef
			defaultHierarchy: LocalDateTable_b6e5a9cc-4464-4114-a477-f726041a56a0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column delivery_days
		dataType: int64
		formatString: 0
		lineageTag: d2a8cf66-bf7c-42ac-9b21-d89fd85134b4
		summarizeBy: sum
		sourceColumn: delivery_days

		annotation SummarizationSetBy = Automatic

	column is_valid_order
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 18711423-7264-4759-bc09-b55605ce9309
		summarizeBy: none
		sourceColumn: is_valid_order

		annotation SummarizationSetBy = Automatic

	column total_item_price
		dataType: double
		lineageTag: e2a0123d-381a-4f86-85f4-c54067ce25bf
		summarizeBy: sum
		sourceColumn: total_item_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_freight
		dataType: double
		lineageTag: bb8d91e8-5f32-476f-b8d8-a964dc0cf9a2
		summarizeBy: sum
		sourceColumn: total_freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_payment_value
		dataType: double
		lineageTag: 8f8b779f-f98f-4dbb-9047-8f105a55b4f4
		summarizeBy: sum
		sourceColumn: total_payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: 5b962d3a-102a-491f-a51f-d8acf063a0cb
		summarizeBy: sum
		sourceColumn: review_score

		annotation SummarizationSetBy = Automatic

	column gold_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: dfa52271-8e48-454f-ba71-253ed6eddf87
		summarizeBy: none
		sourceColumn: gold_updated_at

		variation Variation
			isDefault
			relationship: 674fcac7-2694-4067-937e-4f3c806d1a31
			defaultHierarchy: LocalDateTable_2d22d4ed-648c-40e2-ad41-b954665212e3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition fact_orders = m
		mode: import
		source =
				let
				    Source = gold_dwh,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Table name] = "fact_orders")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (6)", each #"Transform File (6)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (6)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (6)", Table.ColumnNames(#"Transform File (6)"(#"Sample File (6)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"order_id", type text}, {"customer_id", type text}, {"order_date_key", Int64.Type}, {"order_status", type text}, {"order_purchase_timestamp", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}, {"delivery_days", Int64.Type}, {"is_valid_order", type logical}, {"total_item_price", type number}, {"total_freight", type number}, {"total_payment_value", type number}, {"review_score", Int64.Type}, {"gold_updated_at", type datetime}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,0,Replacer.ReplaceValue,{"review_score"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"review_score", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

