table fact_order_payments
	lineageTag: d68a84f3-34a7-4f23-9643-2b2ade30efb5

	column order_id
		dataType: string
		lineageTag: 4b47b83c-2739-43de-9c4d-bebe9438696d
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_date_key
		dataType: int64
		formatString: 0
		lineageTag: a93ad3b7-7ed7-4934-b0d3-c0f3c3dfdd5e
		summarizeBy: sum
		sourceColumn: order_date_key

		annotation SummarizationSetBy = Automatic

	column fact_payment_id
		dataType: int64
		formatString: 0
		lineageTag: b3f5979d-7282-4335-92e1-b20df38897b9
		summarizeBy: sum
		sourceColumn: fact_payment_id

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: 7f2cfc47-3724-4a79-997c-965b2f13a0cf
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	column payment_installments
		dataType: int64
		formatString: 0
		lineageTag: 6e061001-afbc-43f4-b402-278faf1d3dd4
		summarizeBy: sum
		sourceColumn: payment_installments

		annotation SummarizationSetBy = Automatic

	column payment_value
		dataType: double
		lineageTag: b6b6d5ed-86a9-4232-bb65-ddecae8e661d
		summarizeBy: sum
		sourceColumn: payment_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gold_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 79bb25b4-9d9c-481d-ab99-e6b12fc0e633
		summarizeBy: none
		sourceColumn: gold_updated_at

		variation Variation
			isDefault
			relationship: efa26aca-31c6-434d-a911-eae9009184e5
			defaultHierarchy: LocalDateTable_907818c1-5aa1-4fad-8cff-6fefc7cf365f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition fact_order_payments = m
		mode: import
		source =
				let
				    Source = gold_dwh,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Table name] = "fact_order_payments")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (8)", each #"Transform File (8)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (8)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (8)", Table.ColumnNames(#"Transform File (8)"(#"Sample File (8)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"order_id", type text}, {"order_date_key", Int64.Type}, {"fact_payment_id", Int64.Type}, {"payment_type", type text}, {"payment_installments", Int64.Type}, {"payment_value", type number}, {"gold_updated_at", type datetime}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each [order_date_key] <> null and [order_date_key] <> "")
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

