table gold_dwh
	lineageTag: be988cde-92e9-48bc-8f97-df8a0627b8bd

	column Extension
		dataType: string
		lineageTag: 187ec9e3-54bb-4ed2-ae35-1a80c2e475cb
		summarizeBy: none
		sourceColumn: Extension

		annotation SummarizationSetBy = Automatic

	column 'Date accessed'
		dataType: dateTime
		formatString: General Date
		lineageTag: b355f108-12df-483f-a18b-485c9795a3c8
		summarizeBy: none
		sourceColumn: Date accessed

		variation Variation
			isDefault
			relationship: 2a9d31c4-622d-45a3-8614-a83656961b1b
			defaultHierarchy: LocalDateTable_6a769643-4ef3-41e7-aa77-e47b0c0a4e93.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Date modified'
		dataType: dateTime
		formatString: General Date
		lineageTag: dbb94827-fb2c-435b-8f35-e7f60801e12b
		summarizeBy: none
		sourceColumn: Date modified

		variation Variation
			isDefault
			relationship: 5004fb92-6c35-4394-82ed-3a042bcfff14
			defaultHierarchy: LocalDateTable_b55f75e6-bb1c-46b2-9664-59b951d68ab9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Date created'
		dataType: dateTime
		formatString: General Date
		lineageTag: 05d44dbc-e418-4e45-aed3-ca0a3f025abb
		summarizeBy: none
		sourceColumn: Date created

		variation Variation
			isDefault
			relationship: 931196bd-cdc8-4934-9870-252b4ced158e
			defaultHierarchy: LocalDateTable_c26f09ab-d836-4828-bdb0-7d83686514fe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Folder Path'
		dataType: string
		lineageTag: cdf2f469-f0e1-46e7-a3a2-57c4b0b4b6d7
		summarizeBy: none
		sourceColumn: Folder Path

		annotation SummarizationSetBy = Automatic

	column 'Name.1'
		dataType: string
		lineageTag: 0229a441-d5e1-495b-aae7-bdfde1a161ac
		summarizeBy: none
		sourceColumn: Name.1

		annotation SummarizationSetBy = Automatic

	column 'Name.2'
		dataType: string
		lineageTag: 33bbe038-7172-417d-9563-d5c7f3bb5250
		summarizeBy: none
		sourceColumn: Name.2

		annotation SummarizationSetBy = Automatic

	column 'Name.3'
		dataType: string
		lineageTag: 9fc9ccbb-a49a-4834-bc8c-7897a1618e2d
		summarizeBy: none
		sourceColumn: Name.3

		annotation SummarizationSetBy = Automatic

	column 'Transform File'
		dataType: string
		lineageTag: c17a6243-1110-470d-92f3-0abfb3c620ba
		summarizeBy: none
		sourceColumn: Transform File

		annotation SummarizationSetBy = Automatic

	column 'Table name'
		dataType: string
		lineageTag: 591c62ab-2f09-42b2-9500-e2b7aa4b99c1
		summarizeBy: none
		sourceColumn: Table name

		annotation SummarizationSetBy = Automatic

	partition gold_dwh = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\84352\Downloads\gold_dwh\content\gold_dwh"),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Extension] = ".parquet")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Invoke Custom Function1", "Name", Splitter.SplitTextByDelimiter(".", QuoteStyle.Csv), {"Name.1", "Name.2", "Name.3"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Name.1", type text}, {"Name.2", type text}, {"Name.3", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Folder Path"}),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Removed Duplicates", "Text After Delimiter", each Text.AfterDelimiter([Folder Path], "gold_dwh\content\gold_dwh"), type text),
				    #"Inserted Text After Delimiter1" = Table.AddColumn(#"Inserted Text After Delimiter", "Text After Delimiter.1", each Text.AfterDelimiter([Text After Delimiter], "\"), type text),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Inserted Text After Delimiter1", "Text Before Delimiter", each Text.BeforeDelimiter([Text After Delimiter.1], "\"), type text),
				    #"Removed Columns" = Table.RemoveColumns(#"Inserted Text Before Delimiter",{"Text After Delimiter", "Text After Delimiter.1"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Text Before Delimiter", "Table name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

