Table dim_customers [headercolor: #175e7a] {
	customer_unique_id text(65535) [ pk, unique ]
	customer_id text(65535)
	customer_zip_code_prefix integer
	customer_city text(65535)
	customer_state text(65535)
}

Table dim_sellers [headercolor: #175e7a] {
	seller_id text(65535) [ pk, unique ]
	seller_zip_code_prefix integer
	seller_city text(65535)
	seller_state text(65535)
}

Table dim_products [headercolor: #175e7a] {
	product_id text(65535) [ pk, unique ]
	product_category_name text(65535)
}

Table dim_date [headercolor: #175e7a] {
	date_key integer
	full_date date
	year integer
	month integer
	quarter integer
	day_name text(65535)
	month_name text(65535)
}

Table dim_orders [headercolor: #175e7a] {
	order_id text(65535) [ pk, unique ]
	customer_id text(65535)
	order_status text(65535)
	order_purchase_date_key integer
	order_approved_date_key integer
	order_delivered_carrier_date_key integer
	order_delivered_customer_date_key integer
	order_estimated_delivery_date_key integer
}

Table fact_order_items [headercolor: #175e7a] {
	fact_item_id integer [ pk, unique ]
	order_id text(65535)
	product_id text(65535)
	seller_id text(65535)
	price numeric(10,2)
	freight_value numeric(10,2)
}

Table fact_order_payments [headercolor: #175e7a] {
	fact_payment_id integer [ pk, unique ]
	order_id text(65535)
	payment_type text(65535)
	payment_installments integer
	payment_value numeric(10,2)
}

Table fact_review [headercolor: #175e7a] {
	review_id text(65535) [ pk, not null ]
	order_id text(65535)
	review_comment_title text(65535)
	review_comment_message text(65535)
	review_score integer
}

Table fact_customer_rfm [headercolor: #175e7a] {
	customer_rfm_id integer [ pk, increment, not null ]
	customer_unique_id text(65535)
	analysis_date_key integer
	frequency integer
	monetary numeric(10,2)
	recency integer
}

Table dim_geolocation [headercolor: #175e7a] {
	geolocation_zip_code_prefix integer [ pk, not null ]
	geolocation_lat float
	geolocation_lng float
	geolocation_city text(65535)
	geolocation_state text(65535)
}

Ref fk_dim_products_product_id_fact_order_items {
	dim_products.product_id < fact_order_items.product_id [ delete: no action, update: no action ]
}

Ref fk_dim_sellers_seller_id_fact_order_items {
	dim_sellers.seller_id < fact_order_items.seller_id [ delete: no action, update: no action ]
}

Ref fk_dim_customers_customer_unique_id_fact_customer_rfm {
	dim_customers.customer_unique_id < fact_customer_rfm.customer_unique_id [ delete: no action, update: no action ]
}

Ref fk_fact_orders_fact_order_id_fact_order_payments {
	dim_orders.order_id < fact_order_payments.order_id [ delete: no action, update: no action ]
}

Ref fk_fact_orders_fact_order_id_fact_order_items {
	dim_orders.order_id < fact_order_items.order_id [ delete: no action, update: no action ]
}

Ref fk_dim_geolocation_geolocation_zip_code_prefix_dim_customers {
	dim_geolocation.geolocation_zip_code_prefix - dim_customers.customer_zip_code_prefix [ delete: no action, update: no action ]
}

Ref fk_dim_geolocation_geolocation_zip_code_prefix_dim_sellers {
	dim_geolocation.geolocation_zip_code_prefix - dim_sellers.seller_zip_code_prefix [ delete: no action, update: no action ]
}

Ref fk_dim_date_date_key_fact_orders {
	dim_date.date_key < dim_orders.order_purchase_date_key [ delete: no action, update: no action ]
}

Ref fk_dim_date_date_key_fact_orders {
	dim_date.date_key < dim_orders.order_approved_date_key [ delete: no action, update: no action ]
}

Ref fk_dim_date_date_key_fact_orders {
	dim_date.date_key < dim_orders.order_delivered_carrier_date_key [ delete: no action, update: no action ]
}

Ref fk_dim_date_date_key_fact_orders {
	dim_date.date_key < dim_orders.order_delivered_customer_date_key [ delete: no action, update: no action ]
}

Ref fk_dim_date_date_key_fact_orders {
	dim_date.date_key < dim_orders.order_estimated_delivery_date_key [ delete: no action, update: no action ]
}

Ref fk_dim_orders_order_id_fact_review {
	dim_orders.order_id < fact_review.order_id [ delete: no action, update: no action ]
}

Ref fk_dim_date_date_key_fact_customer_rfm {
	dim_date.date_key < fact_customer_rfm.analysis_date_key [ delete: no action, update: no action ]
}

Ref fk_dim_customers_customer_id_dim_orders {
	dim_customers.customer_id < dim_orders.customer_id [ delete: no action, update: no action ]
}